apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: keycloak-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/storage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
